/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness and database check for uptime monitoring. Reveals nothing else. */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in with email and password. Sets the session cookies. */
        post: operations["sign_in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Swaps the refresh cookie for a new pair of cookies. */
        post: operations["refresh_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ends the session and clears the cookies. Always succeeds. */
        post: operations["sign_out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Who is signed in, from the signed access cookie. No database read. */
        get: operations["current_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What the web app needs to draw itself for this school: name, sections, wording, modules, theme. */
        get: operations["public_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Replaces the school's theme. Refused unless every colour pair passes the readability check. */
        put: operations["save_theme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "ok" | "down";
        };
        Session: {
            user: components["schemas"]["SessionUser"];
            roles: components["schemas"]["RoleClaim"][];
        };
        SessionUser: {
            id: string;
            fullName: string;
            email: string;
        };
        RoleClaim: {
            role: string;
            /** @enum {string} */
            scope: "own" | "assigned" | "section" | "institution";
            section?: string;
        };
        ApiError: {
            error: string;
        };
        SignInBody: {
            email: string;
            password: string;
        };
        PublicConfig: {
            school: {
                name: string;
                shortName: string;
                currency: string;
                timezone: string;
                region: string;
                template: string | null;
            };
            sections: {
                key: string;
                name: string;
            }[];
            modules: {
                [key: string]: boolean;
            };
            terms: {
                [key: string]: string;
            };
            theme: components["schemas"]["Theme"];
        };
        Theme: {
            name: string;
            /** @enum {string} */
            font: "system" | "inter" | "noto-sans";
            shape: {
                radiusCard: number;
                radiusControl: number;
            };
            light: {
                background: string;
                surface: string;
                text: string;
                textMuted: string;
                border: string;
                primary: string;
                primaryText: string;
                ok: string;
                okSoft: string;
                bad: string;
                badSoft: string;
            };
            dark?: {
                background: string;
                surface: string;
                text: string;
                textMuted: string;
                border: string;
                primary: string;
                primaryText: string;
                ok: string;
                okSoft: string;
                bad: string;
                badSoft: string;
            };
        } | null;
        ConfigError: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    sign_in: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInBody"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Wrong email or password. The same answer for an unknown email. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too many recent failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    refresh_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description No valid session. `refresh_in_progress` means retry once. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sign_out: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    current_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        roles: components["schemas"]["RoleClaim"][];
                    };
                };
            };
            /** @description Not signed in, or the access cookie expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    public_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The school's configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
            /** @description This school has not been set up yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigError"];
                };
            };
        };
    };
    save_theme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Theme"];
            };
        };
        responses: {
            /** @description Saved and active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            /** @description The theme is not readable. Nothing was saved. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error: "contrast_check_failed";
                        failures: {
                            /** @enum {string} */
                            mode: "light" | "dark";
                            rule: string;
                            label: string;
                            ratio: number;
                            minimum: number;
                        }[];
                    };
                };
            };
        };
    };
}
