/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness and database check for uptime monitoring. Reveals nothing else. */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in with email and password. Sets the session cookies. */
        post: operations["sign_in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description The second step of sign-in: the six-digit code from the authenticator app (or a recovery code) plus the challenge from sign-in. Sets the session cookies. */
        post: operations["verify_two_factor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts setting up the authenticator app: returns a new secret (to type in or scan) and the address an app can open. Asking again replaces an unconfirmed secret. */
        post: operations["begin_two_factor_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/2fa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Confirms the first code from the app, turns two-step sign-in on, signs the person in (cookies set) and returns ten single-use recovery codes, shown this once. */
        post: operations["enable_two_factor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Swaps the refresh cookie for a new pair of cookies. */
        post: operations["refresh_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ends the session and clears the cookies. Always succeeds. */
        post: operations["sign_out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Asks for a password-reset email. The answer is always 202, whether or not the address has an account, so it cannot be used to find out who is registered. Limited per account and per address. */
        post: operations["request_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sets a new password with the token from the emailed link. The token works once. Ends every session the account had. */
        post: operations["confirm_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Who is signed in, from the signed access cookie. No database read. */
        get: operations["current_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}/two-factor/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Removes a person's two-step sign-in and ends their sessions, so they set it up again at the next sign-in. For a lost phone with no recovery codes. Super Admin only; nobody resets their own. */
        post: operations["reset_two_factor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What the web app needs to draw itself for this school: name, sections, wording, modules, theme. */
        get: operations["public_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Replaces the school's theme. Refused unless every colour pair passes the readability check. */
        put: operations["save_theme"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/site/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The notices, holidays, routines, vacancies and posts the public may read today, by Nepal's clock: live items from their publish day to the end of their hide-after day. Urgent first, then newest. The same for every visitor. */
        get: operations["site_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            database: "ok" | "down";
        };
        Session: {
            user: components["schemas"]["SessionUser"];
            roles: components["schemas"]["RoleClaim"][];
        };
        SessionUser: {
            id: string;
            fullName: string;
            email: string;
        };
        RoleClaim: {
            role: string;
            /** @enum {string} */
            scope: "own" | "assigned" | "section" | "institution";
            section?: string;
        };
        TwoFactorStep: {
            /** @enum {string} */
            twoFactor: "required" | "setup";
            challenge: string;
        };
        ApiError: {
            error: string;
        };
        SignInBody: {
            email: string;
            password: string;
        };
        TwoFactorCodeBody: {
            challenge: string;
            code: string;
        };
        TwoFactorSetupBody: {
            challenge: string;
        };
        SessionWithRecoveryCodes: {
            user: components["schemas"]["SessionUser"];
            roles: components["schemas"]["RoleClaim"][];
            recoveryCodes: string[];
        };
        PasswordResetRequest: {
            email: string;
        };
        WeakPassword: {
            /** @enum {string} */
            error: "weak_password";
            problems: ("too_short" | "too_long" | "common" | "contains_email" | "contains_school_name")[];
        };
        PasswordResetConfirm: {
            token: string;
            password: string;
        };
        AccountsError: {
            error: string;
        };
        PublicConfig: {
            school: {
                name: string;
                shortName: string;
                currency: string;
                timezone: string;
                region: string;
                template: string | null;
            };
            sections: {
                key: string;
                name: string;
            }[];
            modules: {
                [key: string]: boolean;
            };
            terms: {
                [key: string]: string;
            };
            theme: components["schemas"]["Theme"];
        };
        Theme: {
            name: string;
            /** @enum {string} */
            font: "system" | "inter" | "noto-sans";
            shape: {
                radiusCard: number;
                radiusControl: number;
            };
            light: {
                background: string;
                surface: string;
                text: string;
                textMuted: string;
                border: string;
                primary: string;
                primaryText: string;
                ok: string;
                okSoft: string;
                bad: string;
                badSoft: string;
            };
            dark?: {
                background: string;
                surface: string;
                text: string;
                textMuted: string;
                border: string;
                primary: string;
                primaryText: string;
                ok: string;
                okSoft: string;
                bad: string;
                badSoft: string;
            };
        } | null;
        ConfigError: {
            error: string;
        };
        PublicContent: {
            items: components["schemas"]["PublicContentItem"][];
        };
        PublicContentItem: {
            id: string;
            kind: components["schemas"]["ContentKind"];
            title: string;
            /** @description Plain text. A blank line starts a new paragraph. */
            body: string;
            contact: string | null;
            urgent: boolean;
            publishedOn: string;
            hideAfter: string | null;
        };
        /** @enum {string} */
        ContentKind: "notice" | "holiday" | "routine" | "vacancy" | "post";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    sign_in: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInBody"];
            };
        };
        responses: {
            /** @description Signed in (a session, with the cookies set), or the password was right and a second step is needed (a challenge, no session) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"] | components["schemas"]["TwoFactorStep"];
                };
            };
            /** @description Wrong email or password. The same answer for an unknown email. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too many recent failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    verify_two_factor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorCodeBody"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description `invalid_code` (wrong, already used or expired) or `invalid_challenge` (start again from the password) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too many recent failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    begin_two_factor_setup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorSetupBody"];
            };
        };
        responses: {
            /** @description The secret to add to the app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        secret: string;
                        otpauthUri: string;
                    };
                };
            };
            /** @description The challenge is missing, expired or for another step */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Already turned on */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    enable_two_factor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorCodeBody"];
            };
        };
        responses: {
            /** @description Turned on and signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionWithRecoveryCodes"];
                };
            };
            /** @description `invalid_code` or `invalid_challenge` */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description `no_setup`: no secret was started, or it is already on */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Too many recent failed attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    refresh_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description No valid session. `refresh_in_progress` means retry once. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    sign_out: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    request_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description If the address has an account, an email is on its way */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        accepted: true;
                    };
                };
            };
        };
    };
    confirm_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The link is wrong, already used or expired (the same answer for all three) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The new password is not acceptable; the link still works */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeakPassword"];
                };
            };
        };
    };
    current_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        roles: components["schemas"]["RoleClaim"][];
                    };
                };
            };
            /** @description Not signed in, or the access cookie expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reset_two_factor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nobody can reset their own two-step sign-in */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsError"];
                };
            };
            /** @description No such person */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountsError"];
                };
            };
        };
    };
    public_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The school's configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
            /** @description This school has not been set up yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigError"];
                };
            };
        };
    };
    save_theme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Theme"];
            };
        };
        responses: {
            /** @description Saved and active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        theme: components["schemas"]["Theme"];
                    };
                };
            };
            /** @description The theme is not readable. Nothing was saved. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error: "contrast_check_failed";
                        failures: {
                            /** @enum {string} */
                            mode: "light" | "dark";
                            rule: string;
                            label: string;
                            ratio: number;
                            minimum: number;
                        }[];
                    };
                };
            };
        };
    };
    site_content: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ContentKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What is on the site today */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicContent"];
                };
            };
        };
    };
}
